$ANSIBLE_VAULT;1.1;AES256
61626366393631333833313665636261366331373064643433376665616335323865616161363765
3166356335333839313361613536363530653234316265380a323563346636356332653962396133
35663139363566663535303635343533323662643364343036343130363932393935653132323761
6438616234346437320a353266623337336131393936653464373661356165656232366632656362
38633436653939366633356330633533376562396633633661336436346362643632316632616435
66623333656261323631343061303866313964363732383034323166373435306639393765316666
37613961323562646265353465393263366234363736663661336236626533653035616331303936
37323361636638316263616263623538613365666632373838303030636439636137303666343134
36333436373438313830613065353633366666643966626637363430333163643162633063313933
35386434336661633833323531336636353965613362396366333865633334353136653837366137
66353564643034396532303463623961346338623165313433613761653239623038353632636264
35643362336466363364353036366131303336613731396632396534313061623536396163616337
34633365336561363137393533633262626437373832653333323836383863343230383161353036
34393739656339346432323861323561653933306337373231373534376639393761663461616662
66663763643764363439626133323062666337343231396635646235666262323661303637393036
34346563363336633162653565396161613535663231373435373664306134383064326232316634
37373034316334313338363434323235373235663234333665663565303663326363623239623736
61613933666638653037313864343436623036336232646430613461373963373863306237626466
35356535373433356433336537646534616263336531613939636130653038633836366237316364
37373466633665326661316239316132613763613039396633353430396538656539356465313934
32383634636132313964326363623237646132393364313862656562313537323634333134326664
66623134646437663135623763646561356165666365353336616631396636333566343732636433
62343966656136323231393565366564336539363331333137366532303565313532646262313664
39396636393535626433343064353734363039303061343033303338663336353066303163316239
35613930626634616466633266656137653931653835643537616566663365373035633739326335
3130366362393637656436313830336563613836363030613866