$ANSIBLE_VAULT;1.1;AES256
38363833613035643937616432333830346662656432363465323763623538363161623734326538
3638383162326539383634356636643133366632396530380a656466623263613665333835393231
36393839303864323665333436303166396237393535643333323262313032376135353330316663
6663343034303139620a663433363736386437366364393436333531383061646131663761663035
63613937373636386461316536353532623762343136336530666262656162656564343837366366
64303265326561653365316238666566363033393639643139376133393462396630366336366163
62333762633632356639323332373931363033323637316538383439623262306639383333333664
32383836646663373931