$ANSIBLE_VAULT;1.1;AES256
31383163663133396139306466336330656366656436643731656537396433666335633665383039
3030333334343365646466326564633066363739353261300a333038636264353839636234356132
36623961323162376437343538323338333435663162363466663862646331623730373833336430
3233323762353666660a306365643035633864376231396232623230333134656464313661353664
35363361313238383030346638386437393031383833326639383262386134313261666137306164
65343365373937323834383931313530623665356262393139653432396162626233313762333562
36316563666437643063313538636564613231353364396535363130643965333961656164366562
64343530613636643939
