
#------Grafana Role------

- name: Deploy Nginx config
  ansible.builtin.template:
    src: defaults.ini.j2
    dest: "{{ nginx_config_folder }}/default.conf"
    owner: root
    group: root
    mode: '0644'    
  notify: Restart Nginx
    