---
- hosts: webservers_prod
  become: yes
  vars_files:
  - vars/ssh.yml
  tasks:
    - name: Install dependencies
      ansible.builtin.yum:
        name:
          - unzip
          - curl
        state: present

    - name: Check AWS CLI version
      ansible.builtin.command: aws --version
      register: aws_version
      ignore_errors: yes

    - name: Print aws version
      ansible.builtin.debug:
        var: aws_version

    - name: Download AWS CLI v2 if not exists
      when: aws_version.rc != 0 #only when aws is not installed
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644' 

    - name: Unzip AWS CLI
      when: aws_version.rc != 0
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI v2
      when: aws_version.rc != 0
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws
# setup aws credentials manually using aws configure
            









